function leiamnash(){
 return{
  "name": "react",
  "author": "leiamnash",
  "version": "1.0.0", 
  "noPrefix": "react"
 }
}

async function react(event, api, alice) {
try{
const leiamChat = event.body.toLowerCase();
const leiamReactHaha = ["😄", "😆", "😂", "🤣", "😸", "😹"]
const leiamReactSad = ["🥲", "😭", "😢", "😿"]
const leiamReactHeart = ["❤️", "🧡", "💛", "💚", "💙", "💜", "🤎", "🖤", "🤍", "💝", "💖"]
 if (leiamChat.includes("ah") || leiamChat.includes("ha")|| leiamChat.includes("hs") || leiamChat.includes("sh") || leiamChat.includes("wah") || leiamChat.includes("bobo") || leiamChat.includes("bubu") || leiamChat.includes("vovo") || leiamChat.includes("vuvu") || leiamChat.includes("wala") || leiamChat.includes("wla") || leiamChat.includes("zero") || leiamChat.includes("kalbo") || leiamChat.includes("gago") || leiamChat.includes("gagu") || leiamChat.includes("gagi") || leiamChat.includes("ogag") || leiamChat.includes("gaga") || leiamChat.includes("tanga") || leiamChat.includes("mama mo") || leiamChat.includes("lol") || leiamChat.includes("xd") || leiamChat.includes("lmao") || leiamChat.includes("happy") || leiamChat.includes("tawa") || leiamChat.includes("takte") || leiamChat.includes("umay") || leiamChat.includes("umai") || leiamChat.includes("hays") || leiamChat.includes("😄") || leiamChat.includes("😁") || leiamChat.includes("😆") || leiamChat.includes("😅") || leiamChat.includes("😂") || leiamChat.includes("🤣") || leiamChat.includes("😸") || leiamChat.includes("😹") || leiamChat.includes("yawa") || leiamChat.includes("pota") || leiamChat.includes("puta") || leiamChat.includes("tang") || leiamChat.includes("ampt") || leiamChat.includes("amp") || leiamChat.includes("joke") || leiamChat.includes("biro") || leiamChat.includes("kidding") || leiamChat.includes("funny") || leiamChat.includes("saya") || leiamChat.includes("awit") || leiamChat.includes("baog") || leiamChat.includes("oten") || leiamChat.includes("titi") || leiamChat.includes("tt") || leiamChat.includes("tete") || leiamChat.includes("bastos") || leiamChat.includes("manyak") || leiamChat.includes("fbi") || leiamChat.includes("bobu") || leiamChat.includes("bubo")) return api.setMessageReaction(leiamReactHaha[Math.floor(Math.random() * leiamReactHaha.length)], event.messageID, (err) => {}, true);
 if (leiamChat.includes("sad") || leiamChat.includes("aguy") || leiamChat.includes("agoi") || leiamChat.includes("poghati") || leiamChat.includes("pain") || leiamChat.includes("sakit") || leiamChat.includes("iyak") || leiamChat.includes("broken") || leiamChat.includes("patay") || leiamChat.includes("dead") || leiamChat.includes("hu") || leiamChat.includes("cry") || leiamChat.includes("🥲") || leiamChat.includes("😭") || leiamChat.includes("😢") || leiamChat.includes("😿") || leiamChat.includes("condolences") || leiamChat.includes("break") || leiamChat.includes("aray") || leiamChat.includes("aw") || leiamChat.includes("ouch") || leiamChat.includes("hurt") || leiamChat.includes("luha") || leiamChat.includes("rip") || leiamChat.includes("agay") || leiamChat.includes("agoy") || leiamChat.includes("hiwalay")) return api.setMessageReaction(leiamReactSad[Math.floor(Math.random() * leiamReactSad.length)], event.messageID, (err) => {}, true);
  if (leiamChat.includes("bruh") || leiamChat.includes("rip") || leiamChat.includes("huh") || leiamChat.includes("💀")) return api.setMessageReaction(`💀`, event.messageID, (err) => {}, true); 
  if (leiamChat.includes("love") || leiamChat.includes("luv") || leiamChat.includes("sweet") || leiamChat.includes("babe") || leiamChat.includes("baby") || leiamChat.includes("bebe") || leiamChat.includes("bibi") || leiamChat.includes("mwa") || leiamChat.includes("kiss") || leiamChat.includes("😘") || leiamChat.includes("🥰") || leiamChat.includes("😍") || leiamChat.includes("❤️") || leiamChat.includes("🧡") || leiamChat.includes("💛") || leiamChat.includes("💚") || leiamChat.includes("💙") || leiamChat.includes("💜") || leiamChat.includes("🤎") || leiamChat.includes("🖤") || leiamChat.includes("🤍") || leiamChat.includes("♥️") || leiamChat.includes("💘") || leiamChat.includes("💝") || leiamChat.includes("💖") || leiamChat.includes("💗") || leiamChat.includes("💓") || leiamChat.includes("💞") || leiamChat.includes("💕") || leiamChat.includes("💌") || leiamChat.includes("💟") || leiamChat.includes("❣️") || leiamChat.includes("💋") || leiamChat.includes("miss") || leiamChat.includes("thank") || leiamChat.includes("welcome") || leiamChat.includes("salamat") || leiamChat.includes("arigato") || leiamChat.includes("ganda") || leiamChat.includes("beautiful") || leiamChat.includes("beauty")) return api.setMessageReaction(leiamReactHeart[Math.floor(Math.random() * leiamReactHeart.length)], event.messageID, (err) => {}, true);
  if (leiamChat.includes("sana all") || leiamChat.includes("sana lahat") || leiamChat.includes("sanaol") || leiamChat.includes("sanaul") || leiamChat.includes("naul") || leiamChat.includes("chinall") || leiamChat.includes("china all") || leiamChat.includes("chinaall") || leiamChat.includes("china oil") || leiamChat.includes("chinaoil") || leiamChat.includes("naol") || leiamChat.includes("sana tanan") || leiamChat.includes("tani tanan") || leiamChat.includes("( 2 )") || leiamChat.includes("sàna all") || leiamChat.includes("nàol")) return api.setMessageReaction("2️⃣", event.messageID, (err) => {}, true);
  if (leiamChat.includes("woman") || leiamChat.includes("babae") || leiamChat.includes("girl") || leiamChat.includes("gurl") || leiamChat.includes("women") || leiamChat.includes("eabab") || leiamChat.includes("☕")) return api.setMessageReaction("☕", event.messageID, (err) => {}, true);
  if (leiamChat.includes("woah") || leiamChat.includes("wow") || leiamChat.includes("nice") || leiamChat.includes("noice") || leiamChat.includes("amazing")) return api.setMessageReaction("🎆", event.messageID, (err) => {}, true);
  if (leiamChat.includes("fire") || leiamChat.includes("🔥") || leiamChat.includes("hot")) return api.setMessageReaction("🔥", event.messageID, (err) => {}, true);
  if (leiamChat.includes("damn") || leiamChat.includes("sigma") || leiamChat.includes("shes") || leiamChat.includes("🗿") || leiamChat.includes("respect")) return api.setMessageReaction("🗿", event.messageID, (err) => {}, true);
  if (leiamChat.includes("cold") || leiamChat.includes("🥶") || leiamChat.includes("lamig")) return api.setMessageReaction("🥶", event.messageID, (err) => {}, true);
  if (leiamChat.includes("bye") || leiamChat.includes("see you") || leiamChat.includes("night") || leiamChat.includes("dream")) return api.setMessageReaction("🍃", event.messageID, (err) => {}, true);
  if (leiamChat.includes("bot") || leiamChat.includes("leiam") || leiamChat.includes("liam") || leiamChat.includes("🤖") || leiamChat.includes("developer")) return api.setMessageReaction("🤖", event.messageID, (err) => {}, true);
  if (leiamChat.includes("cute") || leiamChat.includes("kawaii") || leiamChat.includes("sexy") || leiamChat.includes("owo") || leiamChat.includes("uwu") || leiamChat.includes("owu") || leiamChat.includes("uwo") || leiamChat.includes(":3") || leiamChat.includes(":>") || leiamChat.includes("please") || leiamChat.includes("🥹")) return api.setMessageReaction("🥹", event.messageID, (err) => {}, true);
  if (leiamChat.includes("pervert") || leiamChat.includes("hentai") || leiamChat.includes("perv") || leiamChat.includes("ero") || leiamChat.includes("ew") || leiamChat.includes("yuck") || leiamChat.includes("yack") || leiamChat.includes("iw") || leiamChat.includes("😼")) return api.setMessageReaction("😼", event.messageID, (err) => {}, true);
 } catch (err) {} 
}

module.exports = {
    react,
    leiamnash
}